# SPDX-FileCopyrightText: 2020 Adriaan de Groot <groot@kde.org>
# SPDX-License-Identifier: GPL-3.0-or-later
---
$schema: https://json-schema.org/schema#
$id: https://calamares.io/schemas/netinstall
additionalProperties: false
type: object
properties:
    groupsUrl: { type: string }
    required: { type: boolean, default: false }
    label:  # Translatable labels
        type: object
        additionalProperties: true
        properties:
            sidebar: { type: string }
            title: { type: string }
    groups: { type: array }  # TODO: the schema for the whole groups file
required: [ groupsUrl ]
